# Site settings
title: Dream Space
email: mhctl@qq.com
description: > # this means to ignore newlines until "baseurl:"
  This is dream space for study, sharing life and tech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: none
github_username:  menghucheng

# Build settings
markdown: kramdown

paginate: 4

author: tiger

gems: [jekyll-paginate]
